SCREEN_WIDTH, SCREEN_HEIGHT = 800, 640

PLAYER_SPEED = 2
MAX_PLAYER_JUMP_HEIGHT = PLAYER_SPEED * 100
PLAYER_ANIMATION_SWITCHING_DELAY = 10 #After how many frames the animation of the player should progress

MAX_SPEED = 10
FALLLING_SPEED = 1
BASE_GRAVITY_PULL = FALLLING_SPEED
MAX_FALL_SPEED = 16
MAX_JUMP_SPEED = -10  # Negative value for jumping up