SCREEN_WIDTH, SCREEN_HEIGHT = 800, 600
TILE_SIZE = 16

PLAYER_SPEED = 2
JUMP_STRENGTH = 10
GRAVITY_STRENGTH = 1
PLAYER_ANIMATION_SWITCHING_DELAY = 10 #After how many frames the animation of the player should progress